---
- hosts: localhost
  user: jamescarr
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.homebrew
    - jamescarr.dotfiles
    - jamescarr.vim-janus

  tasks:
    - name: Install Handy PIP Packages
      pip:
        name: "{{ item }}"
      become: yes
      with_items:
        - virtualenvwrapper
        - awscli



